### ISSUE TITLE
The Shooting Sometimes Doesnt Work

### ISSUE THREAD

**Issue by FortniteBattles** [cauwelsdev/UE4_FPSTemplate#1] opened 2019-02-25 21:42 UTC
Title

**Comment by cauwelsdev** [comment] 2019-05-22 18:56
Check on 4.9.2 with a clean pull (develop branch) and shooting works as intended, there is an ammo counter in which you will run out of bullets which will disable shooting.
AI was also able to shoot, they are line of sight for shooting so cover can break their line of sight.

Closing, feel free to re-open though more information such as UE4 Engine version and who was not able to shoot can help with tracking issues.

**Closed as completed by cauwelsdev** 2019-05-22 18:56 UTC
